cook_room_kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    DishListView,
    DishDetailView,
    DishTypeListView,
    CookListView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    toggle_assign_to_dish,
)

urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish_types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
]


app_name = "kitchen"

templates/includes/footer_background.html
{% load static %}

<footer class="footer pt-5 mt-5">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class=" row">
      <div class="col-md-3 mb-4 ms-auto">
        <div>
          <h6 class="text-gradient text-primary font-weight-bolder">Thank you for your interest</h6>
        </div>

        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Coded by <a href="https://t.me/mrOstapix" target="_blank">O.Turianskyi</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navbar_top.html
<nav class="navbar navbar-light bg-light justify-content-between">
  {% if user.is_authenticated %}
    <a href="{% url 'logout'%}?next={{request.path}}" class="navbar-brand btn btn-sm  bg-gradient-light  btn-round mb-0 me-1 mt-2 mt-md-0">Logout</a>
  {% else %}
    <a href="{% url 'login'%}?next={{request.path}}" class="navbar-brand btn btn-sm  bg-gradient-light  btn-round mb-0 me-1 mt-2 mt-md-0">Login</a>
  {% endif %}
  <a class="nav-link" href="{% url 'kitchen:index' %}">HOME <span class="sr-only">(current)</span></a>
  <a class="nav-link" href="{% url 'kitchen:dish-type-list' %}">DISH TYPES</a>
  <a class="nav-link" href="{% url 'kitchen:dish-list' %}">DISHES</a>
  <a class="nav-link" href="{% url 'kitchen:cook-list' %}">COOKS</a>
  <a href="https://github.com/ostapT/cook-room-kitchen" target="_blank"
       class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">Project on GIT</a>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination link-to-page">
    {% if page_obj.has_previous %}
      <li>
        <button type="button" class="btn bg-gradient-light w-auto me-2"><a href="?{% query_transform request page=page_obj.previous_page_number %}"><<</a></button>

      </li>
    {% endif %}
    <li>
      <button type="button" class="btn bg-gradient-white w-auto me-2">{{ page_obj.number }} of {{ paginator.num_pages }}</button>

    </li>
    {% if page_obj.has_next %}
      <li >
          <button type="button" class="btn bg-gradient-light w-auto me-2"><a href="?{% query_transform request page=page_obj.next_page_number %}">>></a></button>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  {% load static %}
  
<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>