cook_room_kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    DishListView,
    DishDetailView,
    DishTypeListView,
    CookListView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    toggle_assign_to_dish,
)

urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish_types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
]


app_name = "kitchen"

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from cook_room_kitchen import settings


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        blank=True,
        null=True
    )
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )

    class Meta:
        ordering = ["dish_type"]

    def __str__(self) -> str:
        return f"{self.name} price: {self.price}"


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Dish


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
            "email",
        )


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["years_of_experience", "email"]


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."}),
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."}),
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."}),
    )

kitchen/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import (
    CookCreationForm,
    DishForm,
    CookUpdateForm,
    CookSearchForm,
    DishSearchForm,
    DishTypeSearchForm,
)
from kitchen.models import DishType, Cook, Dish


def index(request):
    num_dish_types = DishType.objects.count()
    num_dishes = Dish.objects.count()
    num_cooks = Cook.objects.count()

    context = {
        "num_dish_types": num_dish_types,
        "num_dishes": num_dishes,
        "num_cooks": num_cooks,
    }
    return render(request, "kitchen/index.html", context=context)


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5
    context_object_name = "dish_list"
    success_url = reverse_lazy("kitchen:dish-list")
    queryset = Dish.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Dish.objects.all()
        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    paginate_by = 5
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_list.html"
    success_url = reverse_lazy("kitchen:dish-type-list")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["search_form"] = DishTypeSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class CookListView(LoginRequiredMixin, generic.ListView):
    model = get_user_model()
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")

        context["search_form"] = CookSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = get_user_model().objects.all()
        username = self.request.GET.get("username")

        if username:
            return queryset.filter(username__icontains=username)
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()
    queryset = get_user_model().objects.prefetch_related("dishes")


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    template_name = "kitchen/dish_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = get_user_model()
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = CookUpdateForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    fields = "__all__"
    success_url = reverse_lazy("kitchen:cook-list")


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    if Dish.objects.get(id=pk) in cook.dishes.all():
        cook.dishes.remove(pk)
    else:
        cook.dishes.add(pk)
    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'kitchen:cook-list' %}" class="btn btn-primary">No, thanks</a>
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ cook.username }}
    <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <div class="mx-auto">
    <p><strong>First name:</strong> {{ cook.first_name }}</p>
    <p><strong>Last name:</strong> {{ cook.last_name }}</p>
    <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
    <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>
  </div>


    <h4>Dishes</h4>
  {% if cook.dishes.all %}
    <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Price</th>
          <th>Dish type</th>
          <th></th>
        </tr>
    {% for dish in cook.dishes.all %}
        <tr>
          <td>{{ dish.id }}</td>
          <td><a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a></td>
          <td>{{ dish.price }}</td>
          <td>{{ dish.dish_type }}</td>
        </tr>
      {% endfor %}
      </table>
  {% else %}
    <p>No dishes!</p>
  {% endif %}
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <h1>{{ object|yesno:"Update this,Create new" }} cook profile</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

<div class="content">
  {% block content %}
      <h1>
        Cook List
        <a href="{% url 'kitchen:cook-create' %}" class="btn btn-primary link-to-page">
          Create
        </a>
      </h1>
      <form action="" method="get" class="form-inline">
        {{ search_form|crispy }}
        <input type="submit" value="search" class="btn btn-primary">

      </form>

      {% if cook_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Years of experience</th>
        </tr>
      {% for cook in cook_list %}
        <tr>
          <td>{{ cook.id }}</td>
          <td><a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
          <td>{{ cook.first_name }}</td>
          <td>{{ cook.last_name }}</td>
          <td>{{ cook.years_of_experience }}</td>
        </tr>
      {% endfor %}

      </table>
      {% else %}
        <p>There are no cooks in the kitchen.</p>
      {% endif %}
  {% endblock %}
</div>

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'kitchen:dish-list' %}" class="btn btn-primary">No, thanks</a>
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}
<div class="mx-sm-auto  ">
{% block content %}
  <h1>
    {{ dish.name }}
    <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete this dish
    </a>

    <a href="{% url 'kitchen:dish-update' pk=dish.id%}" class="btn btn-secondary link-to-page">
      Update this dish
    </a>
  </h1>
  <p>Dish type: {{ dish.dish_type.name }}</p>
  <p>Dish price: {{ dish.price }}</p>
  <p>Description:
    {{ dish.description }}
  </p>

  <h1>
    Cooks

    {% if dish in user.dishes.all %}
      <a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" class="btn btn-danger link-to-page">
        Delete me from this dish cooking
      </a>
    {% else %}
      <a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" class="btn btn-success link-to-page">
        Assign me to cooking this dish
      </a>
    {% endif %}

  </h1>

  <ul>
    {% for cook in dish.cooks.all %}
      <li>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
    {% endfor %}
  </ul>
{% endblock %}
</div>

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <h1>{{ object|yesno:"Update this,Create new" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}



{% block content %}
  <h1>
    Dish list
    <a href="{% url 'kitchen:dish-create' %}" class="btn btn-primary link-to-page">
      Create new dish
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="search" class="btn btn-primary">
  </form>
  {% if dish_list %}
    <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Price</th>
          <th>Dish type</th>
          <th></th>
        </tr>
      {% for dish in dish_list %}
        <tr>
          <td>{{ dish.id }}</td>
          <td><a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a></td>
          <td>{{ dish.price }}</td>
          <td>{{ dish.dish_type }}</td>
        </tr>
      {% endfor %}
      </table>
  {% else %}
    <p>There are no dishes yet</p>
  {% endif %}
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-primary">No, thanks</a>
  </form>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dish type list
    <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-primary link-to-page">
      Add new
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="search" class="btn btn-primary">
  </form>
  {% if dish_type_list %}
    <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      {% for dish_type in dish_type_list %}
        <tr>
          <td>{{ dish_type.id }}</td>
          <td>{{ dish_type.name }}</td>
          <td><a href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}" class="btn btn-secondary">UPDATE</a></td>
          <td><a href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}" class="btn btn-danger">DELETE</a></td>
        </tr>
      {% endfor %}
      </table>
  {% else %}
    <p>There are no dish types yet</p>
  {% endif %}
{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}

{% load static %}

{% block title %} Material Kit 2 by Creative Tim {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

<header class="header-2">
  <div class="page-header min-vh-75 relative" style="background-image: url('{% static 'img/curved-images/curved.jpg' %}')">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">
            COOK ROOM KITCHEN
          </h1>
          <p class="lead text-white mt-3">It's a simple management system for the kitchen of your cafe or restaurant<br/> </p>
        </div>
      </div>
    </div>

    <div class="position-absolute w-100 z-index-1 bottom-0">
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="moving-waves">
          <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
          <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
          <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
          <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
        </g>
      </svg>
    </div>
  </div>
</header>


<section class="pt-3 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_dishes }}">0</span>+</h1>
              <h5 class="mt-3">Dishes</h5>
              <p class="text-sm">Amazing dishes from all over the world</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"> <span id="state2" countTo="{{ num_dish_types }}">0</span>+</h1>
              <h5 class="mt-3">Dish types</h5>
              <p class="text-sm">All types of dishes. From appetizers to desserts</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary" id="state3" countTo="{{ num_cooks }}">0</h1>
              <h5 class="mt-3">Cooks</h5>
              <p class="text-sm">Only professionals</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block javascripts %}

<script type="text/javascript">

  if (document.getElementById('state1')) {
    const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
    if (!countUp.error) {
      countUp.start();
    } else {
      console.error(countUp.error);
    }
  }
  if (document.getElementById('state2')) {
    const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
    if (!countUp1.error) {
      countUp1.start();
    } else {
      console.error(countUp1.error);
    }
  }
  if (document.getElementById('state3')) {
    const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
    if (!countUp2.error) {
      countUp2.start();
    } else {
      console.error(countUp2.error);
    };
  }
</script>

{% endblock javascripts %}